#pragma once

#define OPENING_PARENTHESIS_PRIORITY 0
#define CLOSING_PARENTHESIS_PRIORITY 1

#define MIN_SUFFIX_OPERATORS_PRIORITY 4

#define DEFAULT_FUNCTION_PRIORITY 11
#define DEFAULT_PREFIX_OPERATOR_PRIORITY 11
#define DEFAULT_POSTFIX_OPERATOR_PRIORITY 15